# fb config file

port=8082
baseURL=""
address=""
log="stdout"
database="/app/database.db"
root="/app/myfiles"
cert=""
key=""
index=""
index_interval=3600
thumb=false
thumb_video=false
cache_root=""

